### ISSUE TITLE
Unable to install theme, missing index.php

### ISSUE THREAD

**Issue by Melvin-mlp** [CubeAtDev/Vagipedia#1]
Hi @CubeAtDev,

I can't install this theme because index.php file is missing from 'vagipedia' folder.

-- Wordpress Version 5.0.3
-- PHP 7.2

**Comment by CubeAtDev** [comment]
Hi @Melvin-mlp ,

the problem is solved. I just make a mistake in the .gitingnore.
Sorry for that.
